//a client component
"use client";
//useActionState->connects a form to the server action and manage the return state
import { useActionState } from "react";
//importing the server action
import { loginAction } from "@/app/actions/auth";

//exporting the component LoginForm
export default function LoginForm() {
  const [state, formAction] = useActionState(loginAction, { error: null });

  return (
    //formAction->special kind of function generated by REACT, it knows:
    //How to gather form defaultValue
    //How to call the server action
    //How to update stae with the return result
    <form action={formAction} className="space-y-4">
      {/* if state and error state */}
      {state?.error && <p className="text-red-600 text-sm">{state.error}</p>}
      {/* input email */}
      <input name="email" type="email" required placeholder="email" className="w-full border p-2" />
      {/* password input */}
      <input name="password" type="password" required placeholder="password" className="w-full border p-2" />
      {/* submit input */}
      <button type="submit" className="w-full bg-brand text-white py-2">Sign in</button>
    </form>
  );
}