// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Link from "next/link";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     // <html
//     //   lang="en"
//     //   className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     // >
//     //   <body className="min-h-full flex flex-col">{children}</body>
//     // </html>

//     <html lang="en">
//       <body className="min-h-screen flex flex-col">
//         <header className="border-b bg-white">
//           <nav className="max-w-5xl mx-auto flex items-center justify-between p-4">
//             <Link href="/" className="font-bold text-xl">Mctaba</Link>
//             <div className="flex gap-6">
//               <Link href="/product">Phones</Link> 
//                <Link href="/about">About</Link>
//               <Link href="/contact">Contact</Link>
//             </div>
//           </nav>
//         </header>

//         <main className="flex-1">{children}</main>

//         <footer className="border-t p-4 text-center text-sm text-gray-500">
//           &copy; {new Date().getFullYear()} Mctaba Shop
//         </footer>
//       </body>
//     </html>
//   );
// }



import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import CartIndicator from "./components/CartIndicator";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata = {
  title: "Mctaba Shop",
  description: "The best deals on phones and accessories in Kenya",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.variable}>
      <body className="font-sans bg-brand-bg text-brand min-h-screen flex flex-col">
        <header className="border-b bg-white">
          <nav className="max-w-5xl mx-auto flex items-center justify-between p-4">
            <Link href="/" className="font-bold text-xl">Mctaba</Link>

            <div className="flex gap-6">
              <Link href="/products/category/phones">Phones</Link>
              <Link href="/about">About</Link>
              <Link href="/contact">Contact</Link>
              <CartIndicator />
          </div>
          
          </nav>
        </header>
        <main className="flex-1">{children}</main>
        <footer className="border-t p-4 text-center text-sm text-gray-500">
          &copy; {new Date().getFullYear()} Mctaba Shop
        </footer>
      </body>
    </html>
  );
}
